default_stage:
  default_modifiers:
    QuantizationModifier:
      targets: [Linear]
      ignore: ['re:.*lm_head', 're:.*embed_tokens$', 're:.*visual.*', 're:.*linear_attn.*',
        're:.*self_attn\.q_norm$', 're:.*self_attn\.k_norm$', 're:.*input_layernorm$', 're:.*post_attention_layernorm$']
      scheme: FP8
      bypass_divisibility_checks: false
