"""E2E Test for Sandbox Subprocess Injection and System Prompt Advertisement of arc3kit Primitives.

Directly verifies:
  1. Sandboxed Python code executing inside a spawned subprocess
     `sys.executable -I -S -c _SANDBOX_BOOTSTRAP` successfully accesses connected_components, find_path_bfs, etc.
  2. System Prompts generated by tool_agent actually include the arc3kit prompt addendum!
"""

from pathlib import Path
import sys
import numpy as np
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

HARNESS_DIR = REPO_ROOT / "scratchpad/taaf_scored_ref/src/ARC3-Inference"
if HARNESS_DIR.exists() and str(HARNESS_DIR) not in sys.path:
    sys.path.insert(0, str(HARNESS_DIR))


def test_sandbox_subprocess_arc3kit_injection():
    from inference.agent import python_tool_sandbox, tool_agent, prompts
    from submission._duck_sparse.duck_patches_sparse import apply_sparse_sandbox_patches

    # Reset patched flag for clean test run
    if hasattr(python_tool_sandbox, "_arc3kit_sandbox_patched"):
        delattr(python_tool_sandbox, "_arc3kit_sandbox_patched")
    if hasattr(prompts, "_arc3kit_prompts_patched"):
        delattr(prompts, "_arc3kit_prompts_patched")

    status = apply_sparse_sandbox_patches()
    print("Patch status:\n", status)
    assert "patch_sandbox_arc3kit: OK" in status
    assert "patch_prompts_arc3kit: OK" in status

    # Verify System Prompt advertisement in BOTH prompts and tool_agent module bindings
    assert "connected_components" in prompts.PYTHON_ADDENDUM
    assert "connected_components" in tool_agent.PYTHON_ADDENDUM

    grid = [[0] * 64 for _ in range(64)]
    for r in range(10, 15):
        for c in range(10, 15):
            grid[r][c] = 2  # 5x5 block of color 2
    for c in range(50):
        grid[20][c] = 1  # wall

    sandboxed_code = """
objs = connected_components(current_frame)
path = find_path_bfs(current_frame, (5, 5), (25, 5), obstacle_colors={1})
motion = detect_avatar_motion(previous_frame, current_frame)
diff = frame_diff_summary(previous_frame, current_frame)

result = {
    "num_objs": len(objs),
    "obj_colors": [o.color for o in objs],
    "has_path": path is not None,
    "path_len": len(path) if path else 0,
    "moved": motion["moved"],
    "diff_changed": diff["changed"]
}
"""

    initial_state = {
        "current_frame": {"grid": grid, "shape": [64, 64]},
        "history": [],
        "valid_actions": ["UP", "DOWN", "LEFT", "RIGHT", "MOUSE"],
    }

    res = python_tool_sandbox.run_sandboxed_python(
        code=sandboxed_code,
        timeout_seconds=10,
        initial_state=initial_state,
        action_handler=lambda actions: {},
    )

    print("Sandbox execution output:", res)
    assert not res.get("error"), f"Sandbox raised error: {res.get('error')}"
    
    result = res.get("result")
    assert result is not None, f"Result is None! res={res}"
    assert result["num_objs"] == 2, f"Expected 2 objects, got {result['num_objs']}"
    assert result["obj_colors"] == [2, 1]
    assert result["has_path"] == True
    assert result["path_len"] > 0
    print("\n==========================================================================")
    print("SUCCESS: REAL SUBPROCESS SANDBOX INJECTION & PROMPT ADVERTISEMENT VERIFIED 100% E2E!")
    print("==========================================================================\n")


if __name__ == "__main__":
    test_sandbox_subprocess_arc3kit_injection()
