"""Render a GameSpec into a self-contained ARC-AGI-3-style game file.

The emitted file mirrors the structure of the public environment_files games:
a single ARCBaseGame subclass, importing only arcengine (+numpy), loadable via
arc_agi.local_wrapper's exec path. All game state is rebuilt from the embedded
PARAMS literal in on_set_level, so engine level resets/full resets behave
exactly like the public games.
"""

from __future__ import annotations

import json
import pprint
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_HEADER = '''\
# Synthetic ARC-AGI-3-style game generated by tools/synthgen (family={family}).
# Built only on MIT-licensed public arcengine primitives; no external data.
# game_id: {game_id}  sampler seed: {seed}
import numpy as np
from arcengine import ARCBaseGame, Camera, GameAction, Level, Sprite
from arcengine.interfaces import RenderableUserDisplay

PARAMS = {params}


class _Hud(RenderableUserDisplay):
    """Step-budget bar on display row 63 (same idiom as the public games)."""

    def __init__(self, fill: int, empty: int) -> None:
        self.fill = fill
        self.empty = empty
        self.total = 1
        self.remaining = 1

    def reset(self, total: int) -> None:
        self.total = max(1, int(total))
        self.remaining = self.total

    def update(self, remaining: int) -> None:
        self.remaining = max(0, min(int(remaining), self.total))

    def render_interface(self, frame: np.ndarray) -> np.ndarray:
        width = frame.shape[1]
        filled = min(width, round(width * self.remaining / self.total))
        for x in range(width):
            frame[63, x] = self.fill if x < filled else self.empty
        return frame
'''

_NAV_BODY = '''

_CELL = PARAMS["cell_px"]
_ROWS = PARAMS["rows"]
_COLS = PARAMS["cols"]
_COL = PARAMS["colors"]

_DIRS = {{1: (-1, 0), 2: (1, 0), 3: (0, -1), 4: (0, 1)}}


def _cells_sprite(cells, color, name, layer):
    px = np.full((_ROWS * _CELL, _COLS * _CELL), -1, dtype=np.int8)
    for r, c in cells:
        px[r * _CELL : (r + 1) * _CELL, c * _CELL : (c + 1) * _CELL] = color
    return Sprite(pixels=px, name=name, layer=layer, tags=[])


def _cell_sprite(color, name, layer, r, c, mask=None):
    if mask is None:
        px = [[color] * _CELL for _ in range(_CELL)]
    else:
        px = [[color if v else -1 for v in row] for row in mask]
    return Sprite(pixels=px, name=name, layer=layer, x=c * _CELL, y=r * _CELL, tags=[])


def _door_color(ch):
    return {{"A": _COL["door_a"], "B": _COL["door_b"], "S": _COL["switch"]}}[ch]


def _build_level(idx, spec_level):
    grid = spec_level["map"]
    sprites = []
    walls = [(r, c) for r in range(_ROWS) for c in range(_COLS) if grid[r][c] == "#"]
    hazards = [(r, c) for r in range(_ROWS) for c in range(_COLS) if grid[r][c] == "x"]
    sprites.append(_cells_sprite(walls, _COL["wall"], "walls", 0))
    if hazards:
        sprites.append(_cells_sprite(hazards, _COL["hazard"], "hazards", 0))
    for r in range(_ROWS):
        for c in range(_COLS):
            ch = grid[r][c]
            if ch == "G":
                sprites.append(_cell_sprite(_COL["goal"], "goal", 1, r, c))
            elif ch in ("a", "b"):
                sprites.append(_cell_sprite(_COL["key_" + ch], "key_%d_%d" % (r, c), 2, r, c))
            elif ch in ("A", "B", "S"):
                sprites.append(_cell_sprite(_door_color(ch), "door_%d_%d" % (r, c), 2, r, c))
            elif ch == "s":
                sprites.append(_cell_sprite(_COL["switch"], "switch_%d_%d" % (r, c), 2, r, c))
            elif ch == "P":
                sprites.append(
                    _cell_sprite(_COL["player"], "player", 5, r, c, mask=PARAMS["player_shape"])
                )
    return Level(sprites=sprites, grid_size=(_COLS * _CELL, _ROWS * _CELL), name="L%d" % (idx + 1))


_LEVELS = [_build_level(i, lv) for i, lv in enumerate(PARAMS["levels"])]


class {cls}(ARCBaseGame):
    def __init__(self) -> None:
        self._hud = _Hud(_COL["hud_fill"], _COL["hud_empty"]) if PARAMS["hud"] else None
        camera = Camera(
            background=_COL["bg"],
            letter_box=_COL["letterbox"],
            interfaces=[self._hud] if self._hud else [],
        )
        super().__init__(
            game_id="{gid}",
            levels=_LEVELS,
            camera=camera,
            available_actions=PARAMS["available_actions"],
        )

    def on_set_level(self, level: Level) -> None:
        idx = self.level_index
        self._grid = PARAMS["levels"][idx]["map"]
        self._opened = set()
        self._budget = PARAMS["budget"][idx]
        for r in range(_ROWS):
            for c in range(_COLS):
                if self._grid[r][c] == "P":
                    self._pos = (r, c)
        if self._hud:
            self._hud.reset(self._budget)

    def _open_token(self, token: str) -> None:
        self._opened.add(token)
        door_ch = token.upper()
        for r in range(_ROWS):
            for c in range(_COLS):
                if self._grid[r][c] == door_ch:
                    for s in self.current_level.get_sprites_by_name("door_%d_%d" % (r, c)):
                        self.current_level.remove_sprite(s)

    def step(self) -> None:
        if self._hud:
            self._hud.update(self._budget - self._action_count)
        if self._action_count > self._budget:
            self.lose()
            self.complete_action()
            return
        direction = _DIRS.get(self.action.id.value)
        if direction is None:
            self.complete_action()
            return
        r, c = self._pos
        nr, nc = r + direction[0], c + direction[1]
        if not (0 <= nr < _ROWS and 0 <= nc < _COLS):
            self.complete_action()
            return
        ch = self._grid[nr][nc]
        blocked = ch == "#" or (ch in ("A", "B", "S") and ch.lower() not in self._opened)
        if not blocked:
            self._pos = (nr, nc)
            for s in self.current_level.get_sprites_by_name("player"):
                s.set_position(nc * _CELL, nr * _CELL)
            if ch == "x":
                self.lose()
                self.complete_action()
                return
            if ch in ("a", "b") and ch not in self._opened:
                for s in self.current_level.get_sprites_by_name("key_%d_%d" % (nr, nc)):
                    self.current_level.remove_sprite(s)
                self._open_token(ch)
            elif ch == "s" and "s" not in self._opened:
                for s in self.current_level.get_sprites_by_name("switch_%d_%d" % (nr, nc)):
                    s.color_remap(None, _COL["switch_on"])
                self._open_token("s")
            elif ch == "G":
                self.next_level()
        self.complete_action()
'''

_CLICK_BODY = '''

_G = PARAMS["grid"]
_S = PARAMS["obj_size"]
_COL = PARAMS["colors"]
_MASKS = PARAMS["shape_masks"]


def _mask_sprite(mask, color, name, layer, x, y, tags=None):
    px = [[color if v else -1 for v in row] for row in mask]
    return Sprite(pixels=px, name=name, layer=layer, x=x, y=y, tags=tags or [])


def _build_level(idx, spec_level):
    sprites = []
    cue = spec_level.get("cue")
    if cue is not None:
        frame_px = _S + 4
        ring = [
            [1 if r in (0, frame_px - 1) or c in (0, frame_px - 1) else 0 for c in range(frame_px)]
            for r in range(frame_px)
        ]
        sprites.append(_mask_sprite(ring, _COL["legend_frame"], "legend", 1, 1, 1))
        if cue["kind"] == "color":
            swatch = [[1] * _S for _ in range(_S)]
            sprites.append(_mask_sprite(swatch, cue["color"], "cue", 2, 3, 3))
        else:
            sprites.append(_mask_sprite(_MASKS[cue["shape"]], cue["color"], "cue", 2, 3, 3))
    if PARAMS["gate"]:
        gp = PARAMS["gate_px"]
        gate_mask = [[1] * gp for _ in range(gp)]
        gx, gy = PARAMS["gate_xy"]
        sprites.append(_mask_sprite(gate_mask, _COL["gate_off"], "gate", 2, gx, gy, tags=["sys_click"]))
    for i in range(PARAMS["lives"]):
        pip = [[1, 1], [1, 1]]
        sprites.append(_mask_sprite(pip, _COL["life"], "life_%d" % i, 2, _G - 3 - 3 * i, 1))
    for i, obj in enumerate(spec_level["objects"]):
        sprites.append(
            _mask_sprite(
                _MASKS[obj["shape"]], obj["color"], "obj_%d" % i, 3, obj["x"], obj["y"],
                tags=["sys_click"],
            )
        )
    return Level(sprites=sprites, grid_size=(_G, _G), name="L%d" % (idx + 1))


_LEVELS = [_build_level(i, lv) for i, lv in enumerate(PARAMS["levels"])]


class {cls}(ARCBaseGame):
    def __init__(self) -> None:
        self._hud = _Hud(_COL["hud_fill"], _COL["hud_empty"]) if PARAMS["hud"] else None
        camera = Camera(
            background=_COL["bg"],
            letter_box=_COL["letterbox"],
            interfaces=[self._hud] if self._hud else [],
        )
        super().__init__(
            game_id="{gid}",
            levels=_LEVELS,
            camera=camera,
            available_actions=PARAMS["available_actions"],
        )

    def on_set_level(self, level: Level) -> None:
        idx = self.level_index
        self._objects = PARAMS["levels"][idx]["objects"]
        self._alive = set(range(len(self._objects)))
        self._remaining = {{i for i, o in enumerate(self._objects) if o["target"]}}
        self._armed = not PARAMS["gate"]
        self._lives = PARAMS["lives"]
        self._budget = PARAMS["budget"][idx]
        if self._hud:
            self._hud.reset(self._budget)

    def _hit_object(self, gx: int, gy: int):
        for i in self._alive:
            o = self._objects[i]
            dx, dy = gx - o["x"], gy - o["y"]
            if 0 <= dx < _S and 0 <= dy < _S and _MASKS[o["shape"]][dy][dx]:
                return i
        return None

    def step(self) -> None:
        if self._hud:
            self._hud.update(self._budget - self._action_count)
        if self._action_count > self._budget:
            self.lose()
            self.complete_action()
            return
        if self.action.id != GameAction.ACTION6:
            self.complete_action()
            return
        data = self.action.data
        if "x" not in data or "y" not in data:
            self.complete_action()
            return
        point = self.camera.display_to_grid(data["x"], data["y"])
        if point is None:
            self.complete_action()
            return
        gx, gy = point
        if not self._armed:
            ax, ay = PARAMS["gate_xy"]
            gp = PARAMS["gate_px"]
            if ax <= gx < ax + gp and ay <= gy < ay + gp:
                self._armed = True
                for s in self.current_level.get_sprites_by_name("gate"):
                    s.color_remap(None, _COL["gate_on"])
            self.complete_action()
            return
        hit = self._hit_object(gx, gy)
        if hit is None:
            self.complete_action()
            return
        if hit in self._remaining:
            self._remaining.discard(hit)
            self._alive.discard(hit)
            for s in self.current_level.get_sprites_by_name("obj_%d" % hit):
                self.current_level.remove_sprite(s)
            if not self._remaining:
                self.next_level()
        else:
            self._lives -= 1
            for s in self.current_level.get_sprites_by_name("life_%d" % self._lives):
                self.current_level.remove_sprite(s)
            if self._lives <= 0:
                self.lose()
        self.complete_action()
'''

_PUSH_BODY = '''

_CELL = PARAMS["cell_px"]
_ROWS = PARAMS["rows"]
_COLS = PARAMS["cols"]
_COL = PARAMS["colors"]

_DIRS = {{1: (-1, 0), 2: (1, 0), 3: (0, -1), 4: (0, 1)}}


def _cells_sprite(cells, color, name, layer):
    px = np.full((_ROWS * _CELL, _COLS * _CELL), -1, dtype=np.int8)
    for r, c in cells:
        px[r * _CELL : (r + 1) * _CELL, c * _CELL : (c + 1) * _CELL] = color
    return Sprite(pixels=px, name=name, layer=layer, tags=[])


def _cell_sprite(color, name, layer, r, c, mask=None):
    if mask is None:
        px = [[color] * _CELL for _ in range(_CELL)]
    else:
        px = [[color if v else -1 for v in row] for row in mask]
    return Sprite(pixels=px, name=name, layer=layer, x=c * _CELL, y=r * _CELL, tags=[])


def _parse(grid):
    walls, pads, boxes = set(), set(), []
    player = None
    for r in range(_ROWS):
        for c in range(_COLS):
            ch = grid[r][c]
            if ch == "#":
                walls.add((r, c))
            elif ch == "T":
                pads.add((r, c))
            elif ch == "B":
                boxes.append((r, c))
            elif ch == "O":
                pads.add((r, c))
                boxes.append((r, c))
            elif ch == "P":
                player = (r, c)
    return walls, pads, sorted(boxes), player


def _build_level(idx, spec_level):
    walls, pads, boxes, player = _parse(spec_level["map"])
    sprites = [_cells_sprite(sorted(walls), _COL["wall"], "walls", 0)]
    if pads:
        sprites.append(_cells_sprite(sorted(pads), _COL["pad"], "pads", 1))
    for i, (r, c) in enumerate(boxes):
        color = _COL["box_on"] if (r, c) in pads else _COL["box"]
        sprites.append(_cell_sprite(color, "box_%d" % i, 3, r, c))
    pr, pc = player
    sprites.append(_cell_sprite(_COL["player"], "player", 5, pr, pc, mask=PARAMS["player_shape"]))
    return Level(sprites=sprites, grid_size=(_COLS * _CELL, _ROWS * _CELL), name="L%d" % (idx + 1))


_LEVELS = [_build_level(i, lv) for i, lv in enumerate(PARAMS["levels"])]


class {cls}(ARCBaseGame):
    def __init__(self) -> None:
        self._hud = _Hud(_COL["hud_fill"], _COL["hud_empty"]) if PARAMS["hud"] else None
        camera = Camera(
            background=_COL["bg"],
            letter_box=_COL["letterbox"],
            interfaces=[self._hud] if self._hud else [],
        )
        super().__init__(
            game_id="{gid}",
            levels=_LEVELS,
            camera=camera,
            available_actions=PARAMS["available_actions"],
        )

    def on_set_level(self, level: Level) -> None:
        idx = self.level_index
        walls, pads, boxes, player = _parse(PARAMS["levels"][idx]["map"])
        self._walls = walls
        self._pads = pads
        self._boxes = list(boxes)
        self._pos = player
        self._budget = PARAMS["budget"][idx]
        if self._hud:
            self._hud.reset(self._budget)

    def _move_sprite(self, name: str, r: int, c: int) -> None:
        for s in self.current_level.get_sprites_by_name(name):
            s.set_position(c * _CELL, r * _CELL)

    def step(self) -> None:
        if self._hud:
            self._hud.update(self._budget - self._action_count)
        if self._action_count > self._budget:
            self.lose()
            self.complete_action()
            return
        direction = _DIRS.get(self.action.id.value)
        if direction is None:
            self.complete_action()
            return
        dr, dc = direction
        r, c = self._pos
        nr, nc = r + dr, c + dc
        if (nr, nc) in self._walls or not (0 <= nr < _ROWS and 0 <= nc < _COLS):
            self.complete_action()
            return
        if (nr, nc) in self._boxes:
            br, bc = nr + dr, nc + dc
            if (
                (br, bc) in self._walls
                or (br, bc) in self._boxes
                or not (0 <= br < _ROWS and 0 <= bc < _COLS)
            ):
                self.complete_action()
                return
            bi = self._boxes.index((nr, nc))
            self._boxes[bi] = (br, bc)
            self._move_sprite("box_%d" % bi, br, bc)
            new_color = _COL["box_on"] if (br, bc) in self._pads else _COL["box"]
            for s in self.current_level.get_sprites_by_name("box_%d" % bi):
                s.color_remap(None, new_color)
        self._pos = (nr, nc)
        self._move_sprite("player", nr, nc)
        if self._pads and self._pads.issubset(set(self._boxes)):
            self.next_level()
        self.complete_action()
'''

_BODIES = {"nav": _NAV_BODY, "click": _CLICK_BODY, "push": _PUSH_BODY}


def class_name_for(game_id: str) -> str:
    """Matches EnvironmentInfo.set_defaults: first 4 chars, first letter upper."""
    base = game_id.split("-")[0][:4]
    return base[0].upper() + base[1:]


def render_game_py(spec: dict[str, Any]) -> str:
    params = {k: v for k, v in spec.items() if k not in ("solution_levels",)}
    body = _BODIES[spec["family"]]
    header = _HEADER.format(
        family=spec["family"],
        game_id=spec["game_id"],
        seed=spec["seed"],
        params=pprint.pformat(params, width=100, sort_dicts=False),
    )
    return header + body.format(cls=class_name_for(spec["game_id"]), gid=spec["game_id"])


def write_env_dir(spec: dict[str, Any], out_root: Path) -> Path:
    """Write <out_root>/<base>/<version>/{<base>.py, metadata.json, spec.json,
    solution.json} — the exact layout arc_agi.Arcade scans."""
    base, version = spec["game_id"].split("-")
    game_dir = Path(out_root) / base / version
    game_dir.mkdir(parents=True, exist_ok=True)
    (game_dir / f"{base}.py").write_text(render_game_py(spec), encoding="utf-8")
    metadata = {
        "game_id": spec["game_id"],
        "title": base.upper(),
        "default_fps": 8,
        "tags": ["synthgen", spec["family"]],
        "local_dir": str(game_dir),
        "date_downloaded": datetime.now(timezone.utc).isoformat(),
    }
    (game_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    (game_dir / "spec.json").write_text(
        json.dumps({k: v for k, v in spec.items() if k != "solution_levels"}, indent=1),
        encoding="utf-8",
    )
    (game_dir / "solution.json").write_text(
        json.dumps(
            {
                "game_id": spec["game_id"],
                "family": spec["family"],
                "per_level": spec["solution_levels"],
                "trace": [a for lvl in spec["solution_levels"] for a in lvl],
            },
            indent=1,
        ),
        encoding="utf-8",
    )
    return game_dir
